### ISSUE TITLE
How to make fonts themeable ?

### ISSUE THREAD

**Issue by anishroff** [jiecao-fm/SwiftTheme#20]
May be this sound noob but I am looking to make fonts available from theme. Is there any way to achieve this using this awesome library ?

**Comment by shannonchou** [comment]
Hi anishroff, it doesn't have this feature now. But I think it's a good advice. Though it's difficult to cover all scenarios that using font. Especially using plist mode. What is your main scenario? It's easy if you just set font on UILabel. Because we can quickly add "theme_font" property on UILabel.

**Comment by wxxsw** [comment]
@anishroff  I added the `theme_font` attribute to `UILabel`, `UITextField` and `UITextView`, but now only support index mode, I hope this will meet your current needs.

I have released a new version of [0.3.2](https://github.com/jiecao-fm/SwiftTheme/tree/0.3.2).

**Comment by wxxsw** [comment]
I would like to close this issue, if there are problems, please reopen, thank you!
